-- Disable RLS on core tables to allow server-side inserts/updates
ALTER TABLE IF EXISTS tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS meals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS food_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS nutrition_data DISABLE ROW LEVEL SECURITY;

