-- Temporarily disable RLS to unblock writes during approval flow
ALTER TABLE IF EXISTS meals NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS food_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS nutrition_data NO FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS meals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS food_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS nutrition_data DISABLE ROW LEVEL SECURITY;

